[package]
version = "0.0.1" # Semantic Versioning is used: https://semver.org/

# These fields are used primarily for display in the extension browser UI.
title = "Community Release Test"
description = "An extension to test publishing to the community registry"
category = "Example"
keywords = ["example", "C++", "cpp"]
icon = "data/icon.png"
preview_image = "data/preview.png"
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
authors = ["Justin Shrake <jshrake@nvidia.com>"]
repository = "https://github.com/jshrake-nvidia/omni.community.release.test"

# Define the Python modules that this extension provides.
# C++ only extensions need this just so tests don't fail.
[[python.module]]
name = "omni.community.release.test"

# Define the C++ plugins that this extension provides.
[[native.plugin]]
path = "bin/omni.community.release.test.plugin"

# Define the documentation that will be generated for this extension.
[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
